version: '3.1'
services:
    api:
        container_name: desafio-analise-credito-api
        build:
            context: api/
            args:
                - API_VERSION=${API_VERSION}
        ports:
            - '3000:8080'
    app:
       container_name: desafio-analise-credito-app
       image: nginx:1.13
       volumes:
         - ./client/dist:/usr/share/nginx/html
         - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
       ports:
          - "80:80"
